version: "3.7"

services:

  chatwoot_app:
    build:
      context: .  # raiz do seu projeto modificado
      dockerfile: ./docker/dockerfiles/rails.Dockerfile
    image: chatwoot-rails:production
    command: >
      sh -c "echo 'Rails.application.config.active_storage.variant_processor = :mini_magick' > /app/config/initializers/active_storage.rb && bundle exec rails s -p 3000 -b 0.0.0.0"
    entrypoint: docker/entrypoints/rails.sh
    volumes:
      - chatwoot_storage:/app/storage
      - chatwoot_public:/app/public
      - chatwoot_mailer:/app/app/views/devise/mailer
      - chatwoot_mailers:/app/app/views/mailers
    networks:
      - NetAlternativo
    environment:
      - INSTALLATION_NAME=CoAlternativo
      - SECRET_KEY_BASE=4235a04ac8018f8e4aeb485bebe62704
      - FRONTEND_URL=https://chat.colegioalternativo.com.br
      - FORCE_SSL=true
      - DEFAULT_LOCALE=pt_BR
      - TZ=America/Sao_Paulo
      - REDIS_URL=redis://chatwoot_redis:6379
      - POSTGRES_HOST=pgvector
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=17fd8d84132b1b48317e8d95096dfc98
      - POSTGRES_DATABASE=chatwoot
      - ACTIVE_STORAGE_SERVICE=local
      - MAILER_SENDER_EMAIL=chat@colegioalternativo.com.br <chat@colegioalternativo.com.br>
      - SMTP_DOMAIN=colegioalternativo.com.br
      - SMTP_ADDRESS=mail.colegioalternativo.com.br
      - SMTP_PORT=587
      - SMTP_SSL=false
      - SMTP_USERNAME=chat@colegioalternativo.com.br
      - SMTP_PASSWORD=3yFzgwCq3bwD4xt
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=chat@colegioalternativo.com.br
      - SIDEKIQ_CONCURRENCY=10
      - RACK_TIMEOUT_SERVICE_TIMEOUT=0
      - RAILS_MAX_THREADS=5
      - WEB_CONCURRENCY=2
      - ENABLE_RACK_ATTACK=false
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - ENABLE_ACCOUNT_SIGNUP=false
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.chatwoot_app.rule=Host(`chat.colegioalternativo.com.br`)
        - traefik.http.routers.chatwoot_app.entrypoints=websecure
        - traefik.http.routers.chatwoot_app.tls.certresolver=letsencryptresolver
        - traefik.http.routers.chatwoot_app.priority=1
        - traefik.http.routers.chatwoot_app.service=chatwoot_app
        - traefik.http.services.chatwoot_app.loadbalancer.server.port=3000
        - traefik.http.services.chatwoot_app.loadbalancer.passHostHeader=true
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.chatwoot_app.middlewares=sslheader

  chatwoot_sidekiq:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/rails.Dockerfile
    image: chatwoot-rails:production
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - chatwoot_storage:/app/storage
      - chatwoot_public:/app/public
      - chatwoot_mailer:/app/app/views/devise/mailer
      - chatwoot_mailers:/app/app/views/mailers
    networks:
      - NetAlternativo
    environment:
      - INSTALLATION_NAME=CoAlternativo
      - SECRET_KEY_BASE=4235a04ac8018f8e4aeb485bebe62704
      - FRONTEND_URL=https://chat.colegioalternativo.com.br
      - FORCE_SSL=true
      - DEFAULT_LOCALE=pt_BR
      - TZ=America/Sao_Paulo
      - REDIS_URL=redis://chatwoot_redis:6379
      - POSTGRES_HOST=pgvector
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=17fd8d84132b1b48317e8d95096dfc98
      - POSTGRES_DATABASE=chatwoot
      - ACTIVE_STORAGE_SERVICE=local
      - MAILER_SENDER_EMAIL=chat@colegioalternativo.com.br <chat@colegioalternativo.com.br>
      - SMTP_DOMAIN=colegioalternativo.com.br
      - SMTP_ADDRESS=mail.colegioalternativo.com.br
      - SMTP_PORT=587
      - SMTP_SSL=false
      - SMTP_USERNAME=chat@colegioalternativo.com.br
      - SMTP_PASSWORD=3yFzgwCq3bwD4xt
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=chat@colegioalternativo.com.br
      - SIDEKIQ_CONCURRENCY=10
      - RACK_TIMEOUT_SERVICE_TIMEOUT=0
      - RAILS_MAX_THREADS=5
      - WEB_CONCURRENCY=2
      - ENABLE_RACK_ATTACK=false
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - ENABLE_ACCOUNT_SIGNUP=false
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 2048M

  chatwoot_redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes", "--port", "6379"]
    volumes:
      - chatwoot_redis:/data
    networks:
      - NetAlternativo
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 2048M

volumes:
  chatwoot_storage:
    external: true
    name: chatwoot_storage
  chatwoot_public:
    external: true
    name: chatwoot_public
  chatwoot_mailer:
    external: true
    name: chatwoot_mailer
  chatwoot_mailers:
    external: true
    name: chatwoot_mailers
  chatwoot_redis:
    external: true
    name: chatwoot_redis

networks:
  NetAlternativo:
    external: true
    name: NetAlternativo
